### ISSUE TITLE
Is there any update plans?

### ISSUE THREAD

**Issue by aaharu** [kavu/webp-loader#12]
`imagemin` is updated in version 7, and drop supporting Node.js 6.
Please let us know if you plan to update.

**Comment by kavu** [comment]
@aaharu thank you for letting me know! Yes, I'll try to update to Imagemin 7.0 soon.

**Comment by kavu** [comment]
@aaharu just pushed version 0.6.0 with Imagemin 7.0.1 as dependency. Hope that helps!
