### ISSUE TITLE
Generate both images (jpg/png and webp) with hash.

### ISSUE THREAD

**Issue by alizhdanov** [kavu/webp-loader#8]
Hi, 

I'm trying to generate alternate versions for my images, which is working fine. However, when I'm trying add **hashes** , I'm getting a problem.

I'm using part of code from README but adding `[hash]` placeholder

```Javascript
loaders: [
  {
    test: /\.(jpe?g|png)$/i,
    loader: multi(
      'file-loader?name=[name].[hash].webp!webp-loader?{quality: 95}'
      'file-loader?name=[name].[hash].[ext]',
    )
  },
]
```

Which is working, but generating different **hashes** 

So output will be:
```bash
image.12345.jpg
image.67890.webp
```

Can I somehow generate img's with same hashes, like this:

```
image.12345.jpg
image.12345.webp
```

Thanks

**Comment by kavu** [comment]
Thank you for your report! I will investigate it. 

Meanwhile, can you tell what exact version of Webpack do you use? Thanks!

**Comment by makedonec88** [comment]
> Meanwhile, can you tell what exact version of Webpack do you use? Thanks!
* webpack **3.9.1**
* file-loader **1.1.5**
* webp-loader **0.2.1**

**Comment by kavu** [comment]
I investigated this issue again and, unfortunately, I think it is not possible. File hashing is done for specific content, and it is done deep inside `loader-utils`. 

The only thing I can suggest here is something like that, pretty common pattern:

```javascript
loaders: [
  {
    test: /\.(jpe?g|png)$/i,
    loader: multi(
      'file-loader?name=[name].webp?[hash]!webp-loader?{quality: 95}'
      'file-loader?name=[name].[ext]?[hash]',
    )
  },
]
```
